### ISSUE TITLE
删除了段落信息

### ISSUE THREAD

**Issue by liyangorg** [And-ZJ/TranslateHelper#1]
首先感谢大佬~ 小意见: 这样子会把所有的空行也替换成空格, 会看不出段落, 我在我fork分支上修改了下

https://github.com/And-ZJ/TranslateHelper/blob/e7f0fc23e84b90ca76704e176c259f555fd713b1/js/app.js#L229

**Comment by And-ZJ** [comment]
谢谢小伙伴的关注，我今天又看了下我的代码，发现有不少地方写的不好，但是最近有点忙，这部分已经修改了，其他问题，我后面再弄。
