### ISSUE TITLE
Failed to load extension

### ISSUE THREAD

**Issue by lichunhong** [And-ZJ/TranslateHelper#3]
Google Chrome：Version 79.0.3945.117 (Official Build) unknown (64-bit)
Ubuntu 16.04

Error
Could not load extension icon 'img/icon.png'.
Could not load manifest.

**Comment by And-ZJ** [comment]
非常抱歉，目前这个插件在Windows上Chrome使用是基本没问题的（除了没做的功能和没解决的Bug外）。由于现在缺少相应Ubuntu环境，故暂时无法测试这个问题，等后续有时间时，会尝试解决这个问题。谢谢。
注：刚注意到，"img/" 下文件 "icon.PNG" 后缀名是大写的，请您尝试下将 mainfest.json 文件中 第7行的 
"128": "img/icon.png" 
中 png 改成 PNG 试一下呢？

**Comment by lichunhong** [comment]
非常棒！按照你说的，成功了！非常感谢╰(*´︶`*)╯
