### ISSUE TITLE
能否增加搜狗翻译的适配

### ISSUE THREAD

**Issue by HanZhang1995** [And-ZJ/TranslateHelper#4]

**Comment by And-ZJ** [comment]
可以是可以，不过现在工作略忙，等有空时再更新。您可以先试试其他翻译网页哈，例如，谷歌翻译，百度翻译。

**Comment by And-ZJ** [comment]
已经添加了哈，您看看有没有什么问题哈。

但是应用商店的审核速度变慢了，不确定什么时候才能更新。如果有急切需要，请使用本地安装当前源码的方式哈。

**Comment by HanZhang1995** [comment]
感谢作者，哈哈哈

发自我的iPhone

在 2020年11月7日，13:20，ZJ <notifications@github.com> 写道：

﻿

已经添加了哈，您看看有没有什么问题哈。

但是应用商店的审核速度变慢了，不确定什么时候才能更新。如果有急切需要，请使用本地安装当前源码的方式哈。
