### ISSUE TITLE
搜狗翻译的按钮位置存在问题

### ISSUE THREAD

**Issue by HanZhang1995** [And-ZJ/TranslateHelper#6]
![image](https://user-images.githubusercontent.com/41636685/102708861-a1d30200-42e0-11eb-8f7f-aff06dd95d2f.png)
谷歌商店也无法安装此插件

**Comment by And-ZJ** [comment]
谢谢。
按钮位置已经修改了，请下载新代码试试。
应用商店提示无法解压的问题，暂不知道是什么原因，已经上传新的压缩包了（版本0.8.4），正等待审核。

说实话，我有在考虑，是不是创建一个QQ群，交流更方便一点？

**Comment by HanZhang1995** [comment]
你好，搜狗翻译点击复制按钮会复制两遍翻译后的内容

**Comment by And-ZJ** [comment]
谢谢反馈，我改了一下。不过暂时没有考虑上传到谷歌应用商店。如有需要，请直接下载此处的源码哈。
